[package]
name = "iced-app"
version = "0.1.0"
edition = "2021"

[dependencies]
glam = { version = "0.25", features = ["bytemuck"] }
iced = { version = "0.13", features = ["advanced"] }
iced_aw = { version = "0.12" }
rfd = "0.15"
bytemuck = "1.0"
image = "0.25"
